import type { DocsGraph } from '@unterberg/nivel'

export const docsGraph = {
  items: [
    {
      id: 'index',
      kind: 'section',
      items: [
        {
          kind: 'group',
          id: 'get-started',
          title: 'Get started',
          icon: 'Rocket',
          collapsible: {
            isDefaultOpen: true,
          },
          items: [
            {
              kind: 'page',
              id: 'gettingStarted',
              title: 'Getting Started',
              slug: 'getting-started',
              source: 'content/getting-started/content.mdx',
              aliases: ['start'],
              description: 'Understand what Nivel provides and how its structure-first docs model fits a Vike app.',
            },
            {
              kind: 'page',
              id: 'introduction',
              title: 'Introduction',
              slug: 'introduction',
              source: 'content/introduction/content.mdx',
              description:
                'Learn why Nivel treats the docs graph as the source of truth for routes, navigation, layout data, and MDX runtime behavior.',
            },
            {
              kind: 'page',
              id: 'installation',
              title: 'Installation',
              slug: 'installation',
              source: 'content/installation/content.mdx',
              description: 'Install @unterberg/nivel with its Vike, React, Vite, and TypeScript peer dependencies.',
            },
            {
              kind: 'page',
              id: 'quickStart',
              title: 'Quick Start',
              slug: 'quick-start',
              source: 'content/quick-start/content.mdx',
              aliases: ['quickstart'],
              description: 'Scaffold a consumer, generate Nivel pages, and run the standard Vike development workflow.',
            },
            {
              kind: 'page',
              id: 'projectShape',
              title: 'Project Shape',
              slug: 'project-shape',
              source: 'content/project-shape/content.mdx',
              description: 'See which files remain consumer-owned and which files Nivel generates from the docs graph.',
            },
            {
              kind: 'page',
              id: 'firstDocsPage',
              title: 'First Docs Page',
              slug: 'first-docs-page',
              source: 'content/first-docs-page/content.mdx',
              description:
                'Create an MDX page, register it in the docs graph, and generate the matching Vike route files.',
            },
          ],
        },
        {
          kind: 'group',
          id: 'core-concepts',
          title: 'Core concepts',
          collapsible: {
            isDefaultOpen: false,
          },
          icon: 'BookOpen',
          items: [
            {
              kind: 'page',
              id: 'docsGraph',
              title: 'The Docs Graph',
              slug: 'docs-graph',
              source: 'content/docs-graph/content.mdx',
              description: 'Model the complete docs structure with sections, groups, pages, aliases, and metadata.',
            },
            {
              kind: 'page',
              id: 'sectionsGroupsPages',
              title: 'Sections, Groups and Pages',
              slug: 'sections-groups-pages',
              source: 'content/sections-groups-pages/content.mdx',
              description: 'Understand how Nivel turns sections, sidebar groups, and routable pages into navigation.',
            },
            {
              kind: 'page',
              id: 'deterministicResolving',
              title: 'Deterministic Resolving',
              slug: 'deterministic-resolving',
              source: 'content/deterministic-resolving/content.mdx',
              description:
                'See how Nivel normalizes config and graph data into one resolved model for routes and runtime UI.',
            },
            {
              kind: 'page',
              id: 'routesAliases',
              title: 'Routes and Aliases',
              slug: 'routes-aliases',
              source: 'content/routes-aliases/content.mdx',
              description: 'Generate canonical docs routes and optional alias routes from page slugs and aliases.',
            },
            {
              kind: 'page',
              id: 'consumerVsEngine',
              title: 'Consumer-owned vs Engine-owned',
              slug: 'consumer-vs-engine',
              source: 'content/consumer-vs-engine/content.mdx',
              description:
                'Keep content, config, shell files, and theme local while Nivel owns generated routes and runtime primitives.',
            },
          ],
        },
        {
          kind: 'group',
          id: 'guides',
          title: 'Guides',
          icon: 'Signpost',
          collapsible: {
            isDefaultOpen: false,
          },
          items: [
            {
              kind: 'page',
              id: 'vikeIntegration',
              title: 'Using Nivel with Vike',
              slug: 'vike-integration',
              source: 'content/vike-integration/content.mdx',
              description: 'Use createNivelVikeConfig() inside a normal Vike + React consumer shell.',
            },
            {
              kind: 'page',
              id: 'generatedPages',
              title: 'Generated Pages',
              slug: 'generated-pages',
              source: 'content/generated-pages/content.mdx',
              description:
                'Understand what appears under pages/(nivel-generated) and why it should not be edited by hand.',
            },
            {
              kind: 'page',
              id: 'developmentWorkflow',
              title: 'Development Workflow',
              slug: 'development-workflow',
              source: 'content/development-workflow/content.mdx',
              description: 'Wire generate, dev, build, and typecheck scripts so generated docs pages stay current.',
            },
            {
              kind: 'page',
              id: 'sitemapRobots',
              title: 'Sitemap and Robots',
              slug: 'sitemap-robots',
              source: 'content/sitemap-robots/content.mdx',
              description: 'Configure siteUrl and robots behavior for static docs output.',
            },
            {
              kind: 'page',
              id: 'tailwindSetup',
              title: 'Tailwind Setup',
              slug: 'tailwind-setup',
              source: 'content/tailwind-setup/content.mdx',
              description: 'Import Nivel CSS and keep Tailwind theme sources in the consumer.',
            },
            {
              kind: 'page',
              id: 'customTheming',
              title: 'Custom Theming',
              slug: 'custom-theming',
              source: 'content/custom-theming/content.mdx',
              description: 'Keep palette tokens and brand styling consumer-owned while using Nivel layout primitives.',
            },
          ],
        },
        {
          kind: 'group',
          id: 'authoring',
          title: 'Authoring',
          icon: 'PencilLine',
          collapsible: {
            isDefaultOpen: false,
          },
          items: [
            {
              kind: 'page',
              id: 'writingMdx',
              title: 'Writing MDX Pages',
              slug: 'writing-mdx',
              source: 'content/writing-mdx/content.mdx',
              description: 'Author MDX files under the configured content directory and register them in the graph.',
            },
            {
              kind: 'page',
              id: 'builtInMdxComponents',
              title: 'Built-in MDX Components',
              slug: 'built-in-mdx-components',
              source: 'content/built-in-mdx-components/content.mdx',
              description: 'Use Nivel-provided docs components such as Alert, Overview, Link, RepoLink, and Table.',
            },
            {
              kind: 'page',
              id: 'codeBlocks',
              title: 'Code Blocks',
              slug: 'code-blocks',
              source: 'content/code-blocks/content.mdx',
              description: 'Document code with Nivel code block tooling, syntax highlighting, and MDX transforms.',
            },
            {
              kind: 'page',
              id: 'overviewCards',
              title: 'Overview Cards',
              slug: 'overview-cards',
              source: 'content/overview-cards/content.mdx',
              description: 'Build graph-aware landing pages with the Overview component.',
            },
            {
              kind: 'page',
              id: 'alerts',
              title: 'Alerts',
              slug: 'alerts',
              source: 'content/alerts/content.mdx',
              description: 'Highlight important notes, warnings, errors, and success states with Alert.',
            },
            {
              kind: 'page',
              id: 'mermaidDiagrams',
              title: 'Mermaid Diagrams',
              slug: 'mermaid-diagrams',
              source: 'content/mermaid-diagrams/content.mdx',
              description:
                'Add Mermaid diagrams to technical docs where diagrams explain the system better than prose.',
            },
          ],
        },
        {
          kind: 'group',
          id: 'configuration',
          title: 'Configuration',
          icon: 'Settings',
          collapsible: {
            isDefaultOpen: false,
          },
          items: [
            {
              kind: 'page',
              id: 'docsConfig',
              title: '`pages/+docs.ts`',
              slug: 'docs-config',
              source: 'content/docs-config/content.mdx',
              description:
                'Configure site metadata, graph data, routes, theme, brand, head tags, and top bar navigation.',
            },
            {
              kind: 'page',
              id: 'basePathContentDirectory',
              title: 'Base Path and Content Directory',
              slug: 'base-path-content-directory',
              source: 'content/base-path-content-directory/content.mdx',
              description: 'Control public docs URLs and the project-relative directory used for MDX sources.',
            },
            {
              kind: 'page',
              id: 'themeConfiguration',
              title: 'Theme Configuration',
              slug: 'theme-configuration',
              source: 'content/theme-configuration/content.mdx',
              description: 'Map light and dark theme names and choose the default theme preference.',
            },
            {
              kind: 'page',
              id: 'brandHeadFonts',
              title: 'Brand, Head and Fonts',
              slug: 'brand-head-fonts',
              source: 'content/brand-head-fonts/content.mdx',
              description: 'Configure brand text, logos, favicons, Apple touch icons, and font loading.',
            },
            {
              kind: 'page',
              id: 'topBarNavigation',
              title: 'Top Bar Navigation',
              slug: 'top-bar-navigation',
              source: 'content/top-bar-navigation/content.mdx',
              description: 'Use simple links or consumer-owned components for top bar navigation.',
            },
            {
              kind: 'page',
              id: 'socialsPartners',
              title: 'Socials and Partners',
              slug: 'socials-partners',
              source: 'content/socials-partners/content.mdx',
              description: 'Add social links and partner logo metadata to the docs shell.',
            },
          ],
        },
        {
          kind: 'group',
          id: 'api-reference',
          title: 'API Reference',
          icon: 'Braces',
          collapsible: {
            isDefaultOpen: false,
          },
          items: [
            {
              kind: 'page',
              tableOfContents: false,
              id: 'publicEntryPoints',
              title: 'Public Entry Points',
              slug: 'public-entry-points',
              source: 'content/public-entry-points/content.mdx',
              description:
                'Choose the correct @unterberg/nivel package entry point for config, client runtime, MDX, or Tailwind.',
            },
            {
              kind: 'page',
              id: 'types',
              title: 'Types',
              slug: 'types',
              source: 'content/types/content.mdx',
              description:
                'Reference the public DocsConfig, DocsGraph, page, group, section, and resolved runtime types.',
            },
            {
              kind: 'page',
              id: 'clientRuntime',
              title: 'Client Runtime',
              slug: 'client-runtime',
              source: 'content/client-runtime/content.mdx',
              description:
                'Use AppLayout, MetaHead, DocsPage, runtime stores, and theme helpers in the consumer shell.',
            },
            {
              kind: 'page',
              id: 'mdxComponentsApi',
              title: 'MDX Components',
              slug: 'mdx-components-api',
              source: 'content/mdx-components-api/content.mdx',
              description: 'Reference the public MDX components exported from @unterberg/nivel.',
            },
            {
              kind: 'page',
              id: 'nodeRuntime',
              title: 'Node Runtime',
              slug: 'node-runtime',
              source: 'content/node-runtime/content.mdx',
              description: 'Understand the lower-level node runtime helpers used by the CLI, Vike plugin, and tests.',
            },
          ],
        },
        {
          kind: 'group',
          id: 'internals',
          title: 'Internals',
          icon: 'Wrench',
          collapsible: {
            isDefaultOpen: false,
          },
          items: [
            {
              kind: 'page',
              id: 'resolverPipeline',
              title: 'Resolver Pipeline',
              slug: 'resolver-pipeline',
              source: 'content/resolver-pipeline/content.mdx',
              description: 'Trace how docs config and graph data become a normalized resolved docs model.',
            },
            {
              kind: 'page',
              id: 'codeGeneration',
              title: 'Code Generation',
              slug: 'code-generation',
              source: 'content/code-generation/content.mdx',
              description: 'See how Nivel writes generated Vike route files from the resolved docs model.',
            },
            {
              kind: 'page',
              id: 'vitePluginLifecycle',
              title: 'Vite Plugin Lifecycle',
              slug: 'vite-plugin-lifecycle',
              source: 'content/vite-plugin-lifecycle/content.mdx',
              description:
                'Understand how the Vite integration watches docs inputs and keeps generated output synchronized.',
            },
            {
              kind: 'page',
              id: 'mdxPipeline',
              title: 'MDX Pipeline',
              slug: 'mdx-pipeline',
              source: 'content/mdx-pipeline/content.mdx',
              description:
                'Understand the MDX transforms that power headings, definition lists, directives, and code blocks.',
            },
          ],
        },
      ],
    },
  ],
} satisfies DocsGraph
